version: "3.8"

volumes:
  runner-data:

networks:
  elastic:
    external: false
  forgejo:
    external: false

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:1.21-rootless
    container_name: forgejo
    environment:
      - USER_UID=1024
      - USER_GID=100
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
      - FORGEJO__server__DOMAIN="git.nseguin.dev"
      - FORGEJO__server__SSH_DOMAIN="git.nseguin.dev"
      - FORGEJO__server__ROOT_URL="https://git.nseguin.dev/"
      - FORGEJO__service__DISABLE_REGISTRATION=true
      - FORGEJO__indexer__ISSUE_INDEXER_TYPE=elasticsearch
      - FORGEJO__indexer__ISSUE_INDEXER_CONN_STR="http://es01:9200"
      - FORGEJO__indexer__REPO_INDEXER_ENABLED=true
      - FORGEJO__indexer__REPO_INDEXER_TYPE=elasticsearch
      - FORGEJO__indexer__REPO_INDEXER_CONN_STR="http://es02:9200"
      - INSTALL_LOCK=true
      - APP_NAME="nseguin.dev"
      - FORGEJO__server__SSH_PORT=3022
      - FORGEJO__server__SSH_LISTEN_PORT=22
      - FORGEJO__repository__ENABLE_PUSH_CREATE_USER=true
    restart: unless-stopped
    networks:
      - forgejo
      - elastic
    volumes:
      - /mnt/data/forgejo/data:/var/lib/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 3022:22
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=forgejo
      - POSTGRES_DB=forgejo
    networks:
      - forgejo
    volumes:
      - /mnt/data/forgejo/postgres:/var/lib/postgresql/data

  es01:
    image: elasticsearch:8.11.1
    restart: unless-stopped
    container_name: es01
    networks:
      - elastic
    volumes:
      - /mnt/data/forgejo/elasticsearch/es01:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01,es02
      - discovery.seed_hosts=es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  es02:
    image: elasticsearch:8.11.1
    restart: unless-stopped
    container_name: es02
    networks:
      - elastic
    volumes:
      - /mnt/data/forgejo/elasticsearch/es02:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01,es02
      - discovery.seed_hosts=es01
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  docker-in-docker:
    image: docker:dind
    privileged: true
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false"]
    depends_on:
      - forgejo
  runner-register:
    image: code.forgejo.org/forgejo/runner:3.3.0
    links:
      - docker-in-docker
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
    depends_on:
      - docker-in-docker
    volumes:
      - runner-data:/data
    user: 0:0
    command: >-
      bash -ec '
      while : ; do
        sleep 5 ;
        forgejo-runner create-runner-file --instance https://git.nseguin.dev --name docker-runner --secret 7c31591e8b67225a116d4a4519ea8e507e08f71f && break ;
      done ;
      forgejo-runner generate-config > config.yml ;
      sed -i -e "s|network: .*|network: host|" config.yml ;
      sed -i -e "s|labels: \[\]|labels: \[\"docker:docker://alpine:3.18\"\]|" config.yml ;
      chown -R 1000:1000 /data
      '

  runner-daemon:
    image: code.forgejo.org/forgejo/runner:3.3.0
    restart: on-failure:3
    links:
      - docker-in-docker
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
    depends_on:
      runner-register:
        condition: service_completed_successfully
    volumes:
      - runner-data:/data
    command: "forgejo-runner --config config.yml daemon"
