version: "3.8"

networks:
  forgejo:
    external: false

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:1.21-rootless
    container_name: forgejo
    environment:
      - USER_UID=1024
      - USER_GID=100
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
      - FORGEJO__server__DOMAIN="git.nseguin.dev"
      - FORGEJO__server__SSH_DOMAIN="git.nseguin.dev"
      - FORGEJO__server__ROOT_URL="https://git.nseguin.dev/"
      - FORGEJO__service__DISABLE_REGISTRATION=true
      - FORGEJO__indexer__ISSUE_INDEXER_TYPE=db
      - INSTALL_LOCK=true
      - APP_NAME="nseguin.dev"
      - FORGEJO__server__SSH_PORT=3022
      - FORGEJO__server__SSH_LISTEN_PORT=22
    restart: unless-stopped
    networks:
      - forgejo
    volumes:
      - /mnt/data/forgejo/data:/var/lib/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 3022:22
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=forgejo
      - POSTGRES_DB=forgejo
    networks:
      - forgejo
    volumes:
      - /mnt/data/forgejo/postgres:/var/lib/postgresql/data
